#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("MonkeyArms.LockedAddressBook.Android.Resource", IsApplication=true)]

namespace MonkeyArms.LockedAddressBook.Android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int app_background = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int app_icon_114 = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int app_icon_29 = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int app_icon_50 = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int app_icon_57 = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int app_icon_58 = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int app_icon_72 = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int header_background = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int Icon = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int mono = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int OrangeButtonBackground = 2130837514;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060002
			public const int contactDetailsListVIew = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int contactsListView = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int imageView1 = 2131099652;
			
			// aapt resource value: 0x7f060000
			public const int labelTextView = 2131099648;
			
			// aapt resource value: 0x7f060005
			public const int passwordText = 2131099653;
			
			// aapt resource value: 0x7f060006
			public const int submitButton = 2131099654;
			
			// aapt resource value: 0x7f060001
			public const int valueTextView = 2131099649;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int ContactDetailItem = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int ContactDetailsList = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int ContactListItem = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int ContactsListLayout = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Main = 2130903044;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int enterPasswordPlaceholder = 2130968576;
			
			// aapt resource value: 0x7f040003
			public const int firstNameLabel = 2130968579;
			
			// aapt resource value: 0x7f040002
			public const int incorrectPassword = 2130968578;
			
			// aapt resource value: 0x7f040004
			public const int lastNameLabel = 2130968580;
			
			// aapt resource value: 0x7f040001
			public const int submitLabel = 2130968577;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int LoginScreenItem = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int TableItem = 2131034113;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
